name: Build check
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - main

jobs:
  compile:
    strategy:
      matrix:
        os: [
          ubuntu-latest,
          windows-latest
#          macos-latest
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Verify Terraform version
        run: terraform --version
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: ~1.23.0
      - name: Lint Terraform
        if: runner.os == 'Linux'
        run: cd terraform && make check-fmt
      - name: Lint Go
        if: runner.os == 'Linux'
        run: make simple-lint
      - name: Compile tests
        run: |
          echo "Compile tests"
          make compile
